name: ufw
version: 0.36pre-16.4
architectures: [amd64]
summary: ufw (Uncomplicated Firewall)
description: ufw as a snap
confinement: strict
grade: stable

apps:
  srv:
    command: bin/srv
    daemon: simple
    plugs: [ firewall-control ]
  ufw:
    command: bin/cli
    plugs: [ firewall-control ]
  init:
    command: bin/init
    plugs: [ firewall-control ]
  doc:
    command: bin/doc
#  shell
#    command: bin/shell

parts:
  wrapper:
    plugin: dump
    source: files/
    stage-packages:
    - ipset
